openapi: 3.1.0
info:
  title: AuthCore API
  version: 1.0.0
  description: |
    AuthCore is a hub where all authentication flows converge. Provides user registration, login, email verification, token validation, and logout.
  contact:
    name: Aerosimo Ltd
    url: https://aerosimo.com
    email: info@aerosimo.com
servers:
  - url: https://ominet.aerosimo.com:9443/authcore
    description: Production server
paths:
  /auth/register:
    post:
      summary: Register a new user
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                password:
                  type: string
              required:
                - username
                - email
                - password
      responses:
        "200":
          description: Registration success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIResponseDTO'
        "409":
          description: Email already registered
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIResponseDTO'
        "400":
          description: Invalid password or request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIResponseDTO'

  /auth/verify:
    post:
      summary: Verify email using token
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
              required:
                - token
      responses:
        "200":
          description: Email verified
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIResponseDTO'
        "400":
          description: Invalid or expired token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIResponseDTO'

  /auth/login:
    post:
      summary: User login
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      responses:
        "200":
          description: Login successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIResponseDTO'
        "401":
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIResponseDTO'

  /auth/validate:
    post:
      summary: Validate auth key
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                authKey:
                  type: string
              required:
                - authKey
      responses:
        "200":
          description: Token is valid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIResponseDTO'
        "401":
          description: Invalid or expired token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIResponseDTO'

  /auth/logout:
    post:
      summary: Logout user session
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                authKey:
                  type: string
              required:
                - authKey
      responses:
        "200":
          description: Logged out successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIResponseDTO'
        "400":
          description: Logout failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIResponseDTO'

components:
  schemas:
    APIResponseDTO:
      type: object
      properties:
        status:
          type: string
          example: success
        message:
          type: string
          example: Operation completed successfully